language: ruby
version: 1.9.3
bundler_args: --without development staging production
before_script:
- sh -e /etc/init.d/xvfb start
script: PADRINO_ENV=travis bundle exec padrino rake
deploy:
  provider: heroku
  api_key:
    secure: gSL5w7Dk9BWHEhn2MnDthDDZaYYpdggEEc9o6+/z+h6ny1v/YAfppT8YN1juT4swXAboRUr8LL+Pj25ELxQg4ok8PA26vAuIVt5A7xIeJElG6JyEChB88/9ouC23O0O+4ya+tl2odZ7sM3viMOtnDhiKhzajgmykGmvADmhzAR0=
  app: macaya1-production
  on:
    repo: nahuelbe/eis-macaya1
